image: /home/elerson/catkin_ws/src/networked_robots_experimetal_data/1euclideanexperiment/exp1/ambiente.png
treefile: /home/elerson/catkin_ws/src/networked_robots_experimetal_data/1euclideanexperiment/steinerData1.dat
resolution: 0.05
