robots:
  1:
    id: 1
    ip: 192.168.0.1
    macaddress: 30:b5:c2:1f:20:a1
    cable_ip: 150.164.212.43

  2:
    id: 2
    ip: 192.168.0.5
    macaddress: 
    cable_ip: 150.164.212.45
  
  3:
    id: 3
    ip: 192.168.0.6
    macaddress: c4:e9:84:0b:8e:30
    cable_ip: 150.164.212.46
  4:
    id: 4
    ip: 192.168.0.7
    macaddress:  30:b5:c2:15:6e:7e
    cable_ip: 150.164.212.46
  5:
    id: 5
    ip: 192.168.0.8
    macaddress: ec:08:6b:0d:5b:19
    cable_ip: 150.164.212.46

configs:
  map: /home/elerson/catkin_ws/src/navigation_roomba/map.png
  treefile: /home/elerson/catkin_ws/src/simulated_experiments/1euclideanexperiment/steinerData1.dat
  resolution: 0.025000
  exit: 1
  simulation: 0
  broadcast_address: 127.255.255.255
  algorithm_port: 39988
  configuration_port: 46544

