configs:
  map: /home/elerson/NetworkedRobotsProject/simulated_experiments/2euclideanexperiment/map/ambiente.png #/home/elerson/catkin_ws/src/navigation_roomba/map.png
  treefile: /home/elerson/NetworkedRobotsProject/simulated_experiments/2euclideanexperiment//steinerData1.dat #/home/elerson/catkin_ws/src/navigation_roomba/steinerData1.dat
  resolution: 0.05
  exit: 1
  simulation: 0
  broadcast_address: 127.255.255.255
  algorithm_port: 39989
  configuration_port: 46545

