robots:
  1:
    id: 1
    ip: 192.168.0.1
    macaddress: a4:4e:31:ed:6d:d4
    cable_ip: 150.164.212.43

  2:
    id: 2
    ip: 192.168.0.2
    macaddress: 1c:4b:d6:85:b0:67
    cable_ip: 150.164.212.45
  
  3:
    id: 3
    ip: 192.168.0.3
    macaddress: 1c:4b:d6:85:bc:20
    cable_ip: 150.164.212.46
  4:
    id: 4
    ip: 192.168.0.4
    macaddress: 48:5d:60:f5:48:8c
    cable_ip: 150.164.212.46
  5:
    id: 5
    ip: 192.168.0.5
    macaddress: 48:5d:60:f5:2c:54
    cable_ip: 150.164.212.46

configs:
  map: /home/elerson/catkin_ws/src/simulated_experiments/1euclideanexperiment/map/ambiente.png
  treefile: /home/elerson/catkin_ws/src/simulated_experiments/1euclideanexperiment/steinerData1.dat
  resolution: 0.05
  exit: 1
  simulation: 1

